services:
  api:
    build: 
      context: ./TaskManagement
      dockerfile: TaskManagement.Api/Dockerfile
    environment:
      - ConnectionStrings__PostgreSQL=Host=db;Port=5432;Database=tasks;Username=postgres;Password=postgres
      - ConnectionStrings__RabbitMq=host=rabbit;port=5672;username=guest;password=guest
    ports: ["5000:8080"]
    depends_on: [db, rabbit]

  asynclogger:
    build: 
      context: ./TaskManagement
      dockerfile: TaskManagement.AsyncLogger/Dockerfile
    environment:
      - ConnectionStrings__RabbitMq=host=rabbit;port=5672;username=guest;password=guest
    depends_on: [rabbit]
  logger:
    build:
      context: ./TaskManagement
      dockerfile: TaskManagement.Logger/Dockerfile
    ports: ["5001:8080"]

  db:
    image: postgres:16
    environment: [POSTGRES_PASSWORD=postgres]
    ports: ["5432:5432"]

  rabbit:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"